#!/usr/bin/env python3
r"""Render a tool README's Compatibility section from its tool.json.

The manifest's `backends[]` block already tells the running binary which
backend versions it knows about. This puts the same facts in the README, so a
reader can answer "will this work on my machine" without installing it:

    <!-- compat:start -->
    <!-- compat:end -->

    tui-kit/tools/render-compat.py --manifest tool.json --readme README.md

Without --check it rewrites the README in place; with --check it only reports
whether the file is up to date, which is what CI runs.

The `tested` column comes from compat/results.jsonl through compat-sync.py, so
what the README claims is what a run in the lab actually proved.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
import textwrap

START = "<!-- compat:start -->"
END = "<!-- compat:end -->"


def wrap(text: str) -> list[str]:
    """Wrap prose the way the family's markdown is written: 79 columns."""
    return textwrap.wrap(text, width=79, break_long_words=False, break_on_hyphens=False)


def render(manifest: dict) -> str:
    """Build the markdown that sits between the two markers."""
    backends = manifest.get("backends") or []
    name = manifest["name"]

    lines = [
        "<!-- Generated by tui-kit/tools/render-compat.py from tool.json. -->",
        "<!-- Edit the manifest, then run `make readme`. -->",
    ]
    if not backends:
        lines.append("")
        lines.extend(wrap(f"`{name}` drives no external backend."))
        return "\n".join(lines)

    lines.append("")
    lines.extend(
        wrap(
            f"`{name}` probes its backend once at startup and shows the version "
            "in the header. A version nobody has tested is marked `(untested)` "
            "there rather than hidden; one below the minimum is marked as such "
            "and the tool still runs."
        )
    )

    for backend in backends:
        lines.append("")
        lines.append(f"### {backend['name']}")
        lines.append("")
        lines.append("| | |")
        lines.append("| --- | --- |")
        lines.append(f"| Binary | `{backend['binary']}` |")
        # A backend whose tools print no version at all (shadow-utils) declares
        # no version command, and the table says so rather than leaving a blank
        # a reader would take for an omission.
        version_command = backend.get("versionCommand") or []
        lines.append(
            f"| Version read with | `{' '.join(version_command)}` |"
            if version_command
            else "| Version read with | nothing: these tools report no version |"
        )
        lines.append(f"| Minimum | {backend.get('minimum') or '—'} |")

        tested = backend.get("tested") or []
        lines.append(
            "| Tested | "
            + (", ".join(f"`{version}`" for version in tested) if tested else "none yet")
            + " |"
        )

        features = backend.get("features") or []
        if features:
            lines.append(
                "| Version-gated features | "
                + ", ".join(f"`{f['name']}` (since {f['since']})" for f in features)
                + " |"
            )

        notes = backend.get("notes") or []
        if notes:
            lines.append("")
            lines.append("| Versions | What changes |")
            lines.append("| --- | --- |")
            for note in notes:
                lines.append(f"| `{note['range']}` | {note['impact']} |")

    lines.append("")
    lines.extend(
        wrap(
            "The tested versions are generated from `compat/results.jsonl`, "
            "which the tool's own smoke test appends to when it runs against a "
            "real machine in [tui-lab](https://github.com/tui-tools/tui-lab)."
        )
    )
    return "\n".join(lines)


def splice(readme: str, body: str) -> str:
    """Put the rendered body between the markers, leaving the rest alone."""
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(readme):
        raise SystemExit(
            f"no {START} … {END} markers in the README: add them around the "
            "Compatibility section first"
        )
    return pattern.sub(f"{START}\n{body}\n{END}", readme, count=1)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default="tool.json", type=pathlib.Path)
    parser.add_argument("--readme", default="README.md", type=pathlib.Path)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero when the README is out of date",
    )
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text())
    body = render(manifest)

    current = args.readme.read_text()
    updated = splice(current, body)

    if args.check:
        if current != updated:
            print(f"{args.readme} is out of date: run `make readme`", file=sys.stderr)
            return 1
        print(f"{args.readme} is up to date")
        return 0

    if current != updated:
        args.readme.write_text(updated)
        print(f"wrote the Compatibility section of {args.readme}")
    else:
        print(f"{args.readme} already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
