#!/usr/bin/env python3
r"""Render a tool README's Install section from its tool.json.

The manifest is the single source for how a tool is installed: the family
website reads it, and so does the README, so the two cannot disagree. This
script replaces everything between the markers

    <!-- install:start -->
    <!-- install:end -->

with one subsection per package manager declared in `install`, in a fixed
order, marking the channels that are not published yet.

    tui-kit/tools/render-install.py --manifest tool.json --readme README.md

Without --check it rewrites the README in place; with --check it only reports
whether the file is already up to date, which is what CI runs.

`{version}` and `{arch}` in a command or a pattern are expanded: the version
comes from --version, or from the repository's latest tag, or falls back to
the placeholder itself when there is no tag yet.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import subprocess
import sys
import textwrap

START = "<!-- install:start -->"
END = "<!-- install:end -->"

# The order the channels are presented in, and how each one is titled. A
# reader picks the row that matches their machine, so the distributions come
# first and the escape hatches last.
CHANNELS = [
    ("pacman", "Arch Linux", "sh"),
    ("aur", "Arch Linux (AUR)", "sh"),
    ("apt", "Debian and Ubuntu", "sh"),
    ("dnf", "Fedora and RHEL", "sh"),
    ("zypper", "openSUSE", "sh"),
    ("binary", "Any distribution, static binary", "sh"),
    ("source", "From source", "sh"),
]

SETUP_URL = "https://tui-tools.github.io/install/"


def latest_version(repo_dir: pathlib.Path) -> str | None:
    """The newest tag in the repository, without its leading v."""
    try:
        out = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0"],
            cwd=repo_dir,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    return out[1:] if out.startswith("v") else out or None


def wrap(text: str) -> list[str]:
    """Wrap prose the way the family's markdown is written: 79 columns."""
    return textwrap.wrap(text, width=79, break_long_words=False, break_on_hyphens=False)


def expand(text: str, version: str | None, arch: str) -> str:
    """Fill the {version} and {arch} placeholders a manifest command carries."""
    if version:
        text = text.replace("{version}", version)
    return text.replace("{arch}", arch)


def render(manifest: dict, version: str | None, arch: str) -> str:
    """Build the markdown that sits between the two markers."""
    install = manifest.get("install", {})
    name = manifest["name"]

    lines: list[str] = []
    lines.append("<!-- Generated by tui-kit/tools/render-install.py from tool.json. -->")
    lines.append("<!-- Edit the manifest, then run `make readme`. -->")

    # What works today comes first; the channels that are still coming are
    # kept, in the same order, under their own heading.
    declared = [(k, t, l) for k, t, l in CHANNELS if k in install]
    ready = [c for c in declared if install[c[0]]["available"]]
    coming = [c for c in declared if not install[c[0]]["available"]]

    def section(channel: tuple[str, str, str]) -> None:
        key, title, lang = channel
        method = install[key]
        suffix = "" if method["available"] else " — coming soon"

        lines.append("")
        lines.append(f"### {title}{suffix}")
        lines.append("")

        if method.get("requires_repo_setup"):
            lines.extend(
                wrap(
                    "Needs the tui-tools repository, which is a "
                    f"[one-time setup]({SETUP_URL})."
                )
            )
            lines.append("")

        lines.append(f"```{lang}")
        lines.extend(expand(method["command"], version, arch).split("\n"))
        lines.append("```")

        note = method.get("note")
        if note:
            lines.append("")
            lines.extend(wrap(note))

    for channel in ready:
        section(channel)

    if coming:
        lines.append("")
        lines.extend(
            wrap(
                "The distribution packages are not published yet. The commands "
                "below are here so you know what they will be; a package "
                "repository at `pkgs.tui.tools` is what turns them on."
            )
        )
        for channel in coming:
            section(channel)

    lines.append("")
    lines.append("### Verify a download")
    lines.append("")
    lines.extend(
        wrap(
            f"Every release of `{name}` ships a `checksums.txt`. Check an archive "
            "against it before installing:"
        )
    )
    lines.append("")
    lines.append("```sh")
    lines.append("sha256sum -c checksums.txt --ignore-missing")
    lines.append("```")

    return "\n".join(lines)


def splice(readme: str, body: str) -> str:
    """Put the rendered body between the markers, leaving the rest alone."""
    pattern = re.compile(
        re.escape(START) + r".*?" + re.escape(END), re.DOTALL
    )
    if not pattern.search(readme):
        raise SystemExit(
            f"no {START} … {END} markers in the README: add them around the "
            "Install section first"
        )
    return pattern.sub(f"{START}\n{body}\n{END}", readme, count=1)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default="tool.json", type=pathlib.Path)
    parser.add_argument("--readme", default="README.md", type=pathlib.Path)
    parser.add_argument(
        "--version",
        default=None,
        help="version to expand {version} with; defaults to the latest tag",
    )
    parser.add_argument(
        "--arch",
        default="amd64",
        help="architecture to expand {arch} with in the README (default: amd64)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero when the README is out of date",
    )
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text())
    version = args.version or latest_version(args.manifest.resolve().parent)
    body = render(manifest, version, args.arch)

    current = args.readme.read_text()
    updated = splice(current, body)

    if args.check:
        if current != updated:
            print(f"{args.readme} is out of date: run `make readme`", file=sys.stderr)
            return 1
        print(f"{args.readme} is up to date")
        return 0

    if current != updated:
        args.readme.write_text(updated)
        print(f"wrote the Install section of {args.readme}")
    else:
        print(f"{args.readme} already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
